### ISSUE TITLE
Program crashes when the only thing I input is *

### ISSUE THREAD

**Issue by durance2** [DoTheEvo/ANGRYsearch#13]
![l46yjas](https://cloud.githubusercontent.com/assets/19888380/15990662/a453a656-30a2-11e6-86f2-dee3ddfe3a71.png)

**Comment by DoTheEvo** [comment]
Thanks for reporting!
[Fixed](https://github.com/DoTheEvo/ANGRYsearch/commit/0a9d3410a98476ee6fa4820ce9fa5a342acc4896)
