### ISSUE TITLE
On Linux Mint, progam opens only via the commandline

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [DoTheEvo/ANGRYsearch#18]
On my Linux Mint 18 x64 Cinnamon, clicking ANGRYsearch's icon in my application menu does nothing. Running the command associated with that icon produces this:

```
python3 /usr/share/angrysearch/angrysearch.py
Traceback (most recent call last):
  File "/usr/share/angrysearch/angrysearch.py", line 10, in <module>
    import PyQt5.QtCore as Qc
ImportError: No module named 'PyQt5'
```
This error is discussed (with reference to programs other than ANGRYsearch) at several places on the web but I did not attempt any of the mooted fixes, for fear of messing up my Python and, thus, my operating system. Please advise! Thanks.
The only way the program will run is via
`ANGRYsearch`

Also, the applet icon (which appears on my system when I run ANGRYsearch via the commandline) is rather dark against most of my panel backgrounds. Moreover, I see no way to disable the applet / stop this icon appearing.

**Comment by DoTheEvo** [comment]
you are missing PyQt5, its the thing that makes the interface, I assume mint is same as ubuntu in this regard and so `sudo apt install python3-pyqt5` should get it for you and all should work

**Comment by ACinnamonUserInUK** [comment]
Thanks for the prompt reply - but, ah, I should have said: no, I have that package.

```
# apt install python3-pyqt5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pyqt5 is already the newest version (5.5.1+dfsg-3ubuntu4).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
```

**Comment by DoTheEvo** [comment]
well the error above says no PyQt5, so it seems rather strange...
will install mint in virtualbox and see whats what in there

you can run python3 and test if you get error or not when [importing PyQt5](http://i.imgur.com/vStdie4.gif)

**Comment by ACinnamonUserInUK** [comment]
Thanks for your work.

Here is what happens when I do as you suggest:

~ $ python3
```
Python 3.5.0 (default, Oct  4 2015, 20:23:35) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'PyQt5'
>>> 
```

**Comment by DoTheEvo** [comment]
well, tested fresh install mint and had zero trouble going with apt install
I then removed the python3-pyqt5, installed pip3 (pythons own package manager) and installed it through pip, worked fine as well, you can give it a try
* install pip for python3 called pip3 - `sudo apt install python3-pip`
* install pyqt5 through pip - `pip install pyqt5`

you should remove the python3-pyqt5 package that you have installed as its obviously not installed properly if python does not see it...

**Comment by ACinnamonUserInUK** [comment]
Thanks.

I removed python3-pyqt5 and then installed python3-pip. All that went fine. However, then this happened:

```
$pip install pyqt5
Collecting pyqt5
  Could not find a version that satisfies the requirement pyqt5 (from versions: )
No matching distribution found for pyqt5
```

**Comment by DoTheEvo** [comment]
>$pip install pyqt5

should be `pip3 install pyqt5`

**Comment by ACinnamonUserInUK** [comment]
Ah yes. Sorry. But still no joy:

```
pip3 install pyqt5
Collecting pyqt5
  Could not find a version that satisfies the requirement pyqt5 (from versions: )
No matching distribution found for pyqt5
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$ pip install --upgrade pip
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages
$ 
```

**Comment by DoTheEvo** [comment]
>pip install --upgrade pip
that should be pip3 even though it said pip, though only for the first one - ``pip3 install --upgrade pip`

dunno really, would expect pip to get it no problem

would try to make sure your system is up to date with sudo apt update / upgrade, which it very likely is...  also would try sudo pip3, but would not expect much change

**Comment by ACinnamonUserInUK** [comment]
I have made some progress - perhaps. Certainly, the plot thickens! Note the bold in what follows.

```
$ **sudo** pip3 install --upgrade pip
The directory '/home/[username - REDACTED BY ME]/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/[username]/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pip
  Downloading pip-8.1.2-py2.py3-none-any.whl (1.2MB)
    100% |████████████████████████████████| 1.2MB 28kB/s 
Installing collected packages: pip
  Found existing installation: pip 7.1.2
    Uninstalling pip-7.1.2:
      Successfully uninstalled pip-7.1.2
Successfully installed pip-8.1.2
~/Desktop/PyQt5_gpl-5.7 $ pip3 install pyqt5
Collecting pyqt5
  Downloading PyQt5-5.7-cp35-cp35m-manylinux1_x86_64.whl (89.8MB)
    100% |████████████████████████████████| 89.8MB 10kB/s 
Collecting sip (from pyqt5)
  Downloading sip-4.18.1-cp35-cp35m-manylinux1_x86_64.whl (60kB)
    100% |████████████████████████████████| 61kB 1.8MB/s 
Installing collected packages: sip, pyqt5
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.5/site-packages/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python3.5/site-packages/pip/wheel.py", line 324, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/local/lib/python3.5/shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/site-packages/sip.so'
```

**Comment by ACinnamonUserInUK** [comment]
Success! Installing pygt5, via pip, with sudo, gave no errors and makes AngrySearch run as it should! Marvellous! I may have improved my system in other respects, too, by getting Python set up more correctly. Thank you ever so much for your speedy and fulsome help. Also, AngrySearch looks like a great program.

**Comment by DoTheEvo** [comment]
glad it worked out
