### ISSUE TITLE
Option to exclude folders is not working, at least as expected

### ISSUE THREAD

**Issue by CottonEaster** [DoTheEvo/ANGRYsearch#19]
My /home/<user>/.config/angrysearch/angrysearch.conf file includes

`directories_excluded=/home/Systemback /var/tmp`

**EDIT**: ah. Probably I misunderstood the phrase 'directory names(no slashes)' in your documentation. Should I have just, e.g. 'Systemback'? Yes, that seems to work! Yet, what if I had more than one folder with that name?

and yet results for subfolders of /home/Systemback appear in the search results. Is there some syntax, that I have omitted from my line, that tells the program to exclude all _sub_folders too?

By the way: I did rebuild the index, but it did not solve the problem.

Thanks.

**Comment by DoTheEvo** [comment]
yeah, ignored directories will be reworked in the next release, code is already there in the last commit... it will work with full path like you used or with just directory name like current functionality, and maybe also with parent directory/target directory combo, for easier use, but I am not sure if the makes it to the release, too many options instead of clean one might be stupid...

**Comment by CottonEaster** [comment]
I am afraid I am still having trouble with exclusions (using a fairly recent version of AngrySearch).

My config file includes:

`directories_excluded=Systemback tmp /mnt/autofs /mnt/autofs/Windows /mnt/aufofs/USB /home/presentations /run/user /Trash /lost+found /root`

Yet, these errors are reported:
```
[Errno 13] Permission denied:
+b'/mnt/autofs/Windows/Windows_Backup/$RECYCLE.BIN/S-1-5-21-3297121681-1545341759-4092395967-1001'
[Errno 13] Permission denied:
+b'/mnt/autofs/Windows/Windows_Backup/$RECYCLE.BIN/S-1-5-21-3297121681-1545341759-4092395967-1018'
[Errno 13] Permission denied: b'/mnt/autofs/Windows/Windows_Backup/System Volume Information'
[Errno 13] Permission denied:
+b'/mnt/autofs/Windows/Windows_Software/$RECYCLE.BIN/S-1-5-21-3297121681-1545341759-4092395967-1001'
[Errno 13] Permission denied:
+b'/mnt/autofs/Windows/Windows_Software/$RECYCLE.BIN/S-1-5-21-3297121681-1545341759-4092395967-1018'
[Errno 13] Permission denied: b'/mnt/autofs/Windows/Windows_Software/Other OSs and LAPTOP/LAPTOP'
[Errno 13] Permission denied: b'/mnt/autofs/Windows/Windows_Software/System Volume Information'
[Errno 13] Permission denied: b'/run/user/1000/gvfs'
```
The errors as such are not the problem; rather, I don't want to stress my Linux laptop by getting it, rather pointlessly, to index the drives on my Windows computer - which is what it seems to be trying to do.

**Comment by DoTheEvo** [comment]
you likely dont use the latest version, will try to make new release within 3 weeks

[here is webm showing ignoring in action](https://s1.webmshare.com/B7oPD.webm)

if you want it right away, just copy paste [the whole script from the last commit](https://raw.githubusercontent.com/DoTheEvo/ANGRYsearch/15e320a42f8c9065db23866f514f98192e691ce9/angrysearch_update_database.py) and replace the one in /usr/share/angrysearch/angrysearch.py

you need to edit it as sudo so you have write privileges.

**Comment by CottonEaster** [comment]
Thank you very much for your work and for the helpful video.

I got a bit confused about just which to update, so I use git to clone the whole of the latest code onto my system.

Result: so far as I can tell, everything works as indended - I see no errors. Good job!
