### ISSUE TITLE
Opening files does not seem to work on Mint

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [DoTheEvo/ANGRYsearch#20]
I've tried for PNG, TXT, PDF and DOCX. Trying to open those files via ANGRY - either by double-clicking the file name, or by right-clicking and selecting 'open' - just opens the folders the files are in. 

Both `~/.local/share/applications/mimeapps.list` and `~/.config/mimeapps.list` exist and are populated on my system. Perhaps there is something wrong with those files.

I have the package, and I reinstalled it to no effect.

My angrysearch.conf file:

```
[General]
angrysearch_lite=true
conditional_mounts_for_autoupdate=
darktheme=false
directories_excluded=Systemback tmp
fast_search_but_no_substring=true
file_manager=nemo
fm_path_doubleclick_selects=true
icon_theme=paper
notifications=false
number_of_results=500
regex_mode=false
row_height=0
typing_delay=true
```

**Comment by DoTheEvo** [comment]
I tested in virtual machine, cinnamon seems to create mimeapps.list in ~/.config once you make any changes through "preferred applications" settings

if I were you, my first try would be deleting(or just renaming) mimeapps.list (all of them) and see what happens
I assume defaults will take over, same as they did in my virtualmachine
when I did 
``xdg-mime query default text/plain``
I got answer xed.desktop which is the default text editor
and so if you execute in terminal command
`xdg-open some_file.txt`
it should be open in xed
and thats the command that angrysearch uses, xdg-open <path to the file>

you might want to check [this archwiki entry](https://wiki.archlinux.org/index.php/Default_applications) on default applications on linux, if you feel like in need of some deeper insight

**Comment by ACinnamonUserInUK** [comment]
Deleting the mimeapps.list files seems to work. Excellent. Thank you.
