### ISSUE TITLE
Position in results list jumps when right-click within that list

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [DoTheEvo/ANGRYsearch#21]
At least sometimes, when I right-click within the results list, my position in that list jumps several entries - and so I end up opening a context-menu for the wrong item. Perhaps you could see if you can replicate. Thanks.

Linux Mint 18 x64 Cinnamon.

**Comment by DoTheEvo** [comment]
yeap, fixed in one of the [recent commits](https://github.com/DoTheEvo/ANGRYsearch/commit/2b981d8719dbecfb558c26d44c9f1dea26f25eee), at least I hope so...

new release should be out soon since this is kinda annoying bug

**Comment by ACinnamonUserInUK** [comment]
Right; I look forward to the new release. Thanks. I'll check back on
your site for announcements. Should we close this issue?
