### ISSUE TITLE
ANGRYsearch does not start up

### ISSUE THREAD

**Issue by andysearch** [DoTheEvo/ANGRYsearch#23]
I'm on arch and installed the package through AUR,
when I want to start the program from my menu it instantly closes

when running in terminal it gives me:

> using qt5ct plugin
> autodetected file manager: thunar
> Traceback (most recent call last):
>   File "/usr/share/angrysearch/angrysearch.py", line 1435, in paint
>     Qw.QStyle.SE_ItemViewItemText, options)
> TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
> Aborted

**Comment by DoTheEvo** [comment]
Try running the latest [release](https://github.com/DoTheEvo/ANGRYsearch/releases)
Just download zip, extract, and in terminal `python3 angrysearch.py`

it very likely will crashes too, as there were not that many changes between the two last versions, especially not in the part where error is reported

next thing to try...   try deleting the config file in ~/.config/angrysearch and why not also the database, in ~/.cache/angrysearch and try running again..

this also wont help very likely, but whatever I say it to get through motions

I assume the version of pyqt5 you have is 5.7-2, `pacman -Qi pyqt5-common`
are you maybe on testing repository or something that would explain crashing on your arch and not on mine... 

Problem is that its not doing on my machine, but will try few virtual arch install..

I probably know how to fix it but you will lose bold text that is highlighting the searched text in results

open the angrysearch.py for editing in some editor and [do this](http://i.imgur.com/1i7Y2lh.gif)
* comment out line containing  `setItemDelegate` 
* commend out name/path lines that use `bold_text` and put word `pass` above them

thnx for reporting

**Comment by DoTheEvo** [comment]
possible fix worth try might be changing line

`Qw.QStyle.SE_ItemViewItemText, options)`
to line
`Qw.QStyle.SE_ItemViewItemText, options, None)`

**Comment by idongyou** [comment]
> possible fix worth try might be changing line

>Qw.QStyle.SE_ItemViewItemText, options)
>to line
>Qw.QStyle.SE_ItemViewItemText, options, None)

It works on my Arch

**Comment by DoTheEvo** [comment]
Meaning you also experienced not starting up?

**Comment by idongyou** [comment]
Yes

**Comment by DoTheEvo** [comment]
ok, that fix will be included in the next version

thnx for reporting

**Comment by DoTheEvo** [comment]
https://github.com/DoTheEvo/ANGRYsearch/releases/tag/v1.0.1
