### ISSUE TITLE
add proper `setup.py`

### ISSUE THREAD

**Issue by DirectorX** [DoTheEvo/ANGRYsearch#24]
hi I think it would be nice to add a `setup.py` to allow easy distribution of this software.

voidlinux/void-packages/pull/4865

**Comment by DoTheEvo** [comment]
Will look in to that.

**Comment by DoTheEvo** [comment]
Added by @lpozo, though unfortunately seems PyQt5 cant be in install_requires so its not really one and be done with all way to install it.
