### ISSUE TITLE
Two suggestions

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [DoTheEvo/ANGRYsearch#25]
(1) Exclude the `mnt` folder by default, so as to avoid index removable media and network-drives,
(2) When user presses 'update', check if the file containing the exclusion list has been modified and, if it has, reload it.

Thanks again for your excellent program - a program that makes me a little less angry.

**Comment by DoTheEvo** [comment]
>Exclude the mnt folder

as I myself mount in there my data drives with music and movies... nope

for a user who wants to exclude /mnt it takes 30sec to find the config and add it there

while if blocked by default, many users might wonder what change happened that their stuff is not in the search results...

>When user presses 'update', check if the file containing the exclusion list has been modified and, if it has, reload it.

hmm, config file is read only on the start, so if angrysearch is running and changes are made in to thefile theres no checking for them.
It is expected that if a user needs to exclude places while running angrysearch it can be done directly in the update dialog, as shown in gif, but will check it out, might be simple thing with not much bug possibility

**Comment by ACinnamonUserInUK** [comment]
`It is expected that if a user needs to exclude places while running angrysearch it can be done directly in the update dialog, as shown in the first gif on the readme page`

Ah yes; I'd forgotten about that - for I'd forgotten that option was filed under 'update'.

Re /mnt: yes, I see your point.
