### ISSUE TITLE
How to search additional drives

### ISSUE THREAD

**Issue by ezmenus** [DoTheEvo/ANGRYsearch#30]
Hello! Thanks for the great software! Maybe I'm not looking in the right place, but I cannot figure out how to index & search all the drives connected to my machine. Only the system drive is accessible. I have 5 drives installed and would like to index them all. My OS is Ubuntu 16.04.Thanks in advance for your assistance!

**Comment by DoTheEvo** [comment]
if the drives are mounted when indexing is being done then they should be searched automatically

just run the update through the interface when you have those 5 drives accessible and search for some uniquely named file on them...  you should get the results and it should open on double click

quick search tells me ubuntu mounts drives in to /media/<your shitty username>/...  so check if its there

**Comment by ezmenus** [comment]
Thank you so much for taking the time to respond! I just found them in the exact location you specified and was coming in to close the issue. So far, ANGRYsearch is working great. Keep up the good work!
