### ISSUE TITLE
Support for breeze icons?

### ISSUE THREAD

**Issue by kupiqu** [DoTheEvo/ANGRYsearch#32]
Could you add support for breeze icons? Thanks in advance!

**Comment by DoTheEvo** [comment]
hmm, default on plasma 5 they claim on their github, feels like I should ...   I thought oxygen was KDE default

**Comment by kupiqu** [comment]
Yes, Oxygen was default in the KDE4 era, but not anymore since Plasma 5, as you just said.

Breeze icons are pretty mature now... So, it would be great if you could support Breeze (don't want to say replace Oxygen, because nostalgic users may like if you keep the option).

**Comment by DoTheEvo** [comment]
https://github.com/DoTheEvo/ANGRYsearch/releases/tag/v1.0.1
