### ISSUE TITLE
Help customizing

### ISSUE THREAD

**Issue by pennybuster** [DoTheEvo/ANGRYsearch#38]
Hi. Thank you for your useful app! It's very fast indeed. Can you help me customize the theme and icons so it looks the same that FSearch with the "dark theme" option enabled? I'm using Arc Darker theme with Flat Remix icons. Thanks a lot!
![screenshot_2017-07-27_02-56-04](https://user-images.githubusercontent.com/498109/28656609-50963f14-7279-11e7-8ef0-b395891234b6.png)

**Comment by DoTheEvo** [comment]
dark theme is just some most common dark theme for Qt (interface framework)
I just applied it if settings are set

if you want to play with it, you can do so relatively easily
edit as root `/usr/share/angrysearch/qdarkstylesheet.qss`
change some color, re-run angrysearch, see the change... 

but considering that the stylesheet has some 1000+ lines...
I recommend using a color picker tool in some painting app like pinta or gimp, on that image you posted. You color pick rows in angrysearch, which will tell your that their exact color is `#201F1F` and the `#201F1F`

then you can search for those colors in the stylesheet file. Many occurances will be find as it might be used on some buttons, on progress bar, some outline for some shit.. but also somewhere there are the alternate background color for rows or some shit like that...

Anyway, [here](https://pastebin.com/j6h2wnbz) is stylesheet where I just quickly changed all occurrences of those colors to the one from fsearch.

![blbalba](http://i.imgur.com/BNKaJ03.png)



 and change them to the color picked from fsearch which is `#404552`

**Comment by pennybuster** [comment]
Thank you very much! Much appreciate it. Happy New Year!!!
