### ISSUE TITLE
Feature request: search for file extensions . .

### ISSUE THREAD

**Issue by CottonEaster** [DoTheEvo/ANGRYsearch#39]
. . without the arcania of regular expressions. Or at least something on the information page - here on Github - about how to search by extension via regular expressions.

Thansk for reading this and I apologise if I have overlooked something.

**Comment by DoTheEvo** [comment]
you can see it in the regex gif

the `$` in regex means end of the file name

so `png$` means find all the files and folders having png at the very end of their name
similarly `^` means the start of the name

if you want to narrow down search to also add some part of file name:

`whatever.*png$` where `.*` between the term and png means anything, any number of times.

`.` - dot means match any character, but it always represent single character so it needs something more
`*` - asterisk is a quantifier, making the previous `.` match zero or ∞ characters.

![regex in action gif](http://i.imgur.com/6dEFvat.gif)

**Comment by CottonEaster** [comment]
Thank you. I will try to remember all that. By the way: searching for `deb$` found .deb files, but also a folder called `deb-format` and various files of this form: deb.compat; deb.control. (That search was conducted with AngrySearch's little box ticked. When the box was unticked, that search finds nothing.)

**Comment by DoTheEvo** [comment]
to make use of regex stuff like `$` you need to press F8 to enable/disable regex mode, indicated by orange background of search input... then `deb$` finds only files and folders that end with deb. Though its quite slow search.

**Comment by CottonEaster** [comment]
Oh. Sorry - I have been doing poorly here.

Thanks for indicating that regex searches are slow; I'd have been wondering what the computer is doing - since it does not seem to give any indication that it is doing work.

**Comment by DoTheEvo** [comment]
three dots lower left corner while searching, number of results when done

**Comment by BurhanDanger** [comment]
I tried fsearch and ANGRYsearch with regex `\.mkv$` . From the looks of it ANGRYsearch is slower.
