### ISSUE TITLE
Is Debian 8 supported?

### ISSUE THREAD

**Issue by wernerbw** [DoTheEvo/ANGRYsearch#4]
Love the AngrySearch.... been using it in Ubuntu and with your idiot-proof instructions, very simple.

However, using Debian 8 now and have this error when 'attempting to test' (python3 angrysearch.py)

![screenshot from 2015-12-22 09 50 53](https://cloud.githubusercontent.com/assets/14228128/11957869/4e1f4382-a892-11e5-9a0b-476dc2b6bf3a.png)

Installed all just as did on Ubuntu, no error before... Thanks.

Bill

**Comment by DoTheEvo** [comment]
Double check if you have python3-pyqt5 package

**Comment by wernerbw** [comment]
k, got it.... Think I dropped the '3' in python3-pyqt5  Reinstalled all fresh; now works.  Thanks.
And, sorry for the mistake.

**Comment by Zangwill** [comment]
python3 -m pip install pyqt5
