### ISSUE TITLE
'close_on_open=false' not honoured

### ISSUE THREAD

**Issue by CottonEaster** [DoTheEvo/ANGRYsearch#43]
AngrySearch version: cannot determine, but installed a few months ago from Git
Mint 18.3 x64 Cinnamon

`angrysearch.conf` snippet:

`close_on_open=false`

Observed behaviour: please see [this video](https://app.box.com/s/dlejxoif7x1criujm617vsjprgit5evq).

**Comment by DoTheEvo** [comment]
I think I was undecided about the term used, and I switched from close_to_open to close_on_execute

delete open in config, change execute to false I guess, or delete whole config and let it be remade again on next run/close

**Comment by CottonEaster** [comment]
Oh, so in fact there is no option to handle opening an item (display a folder's contents, or perhaps displaying a files contents), on the one hand, an executing an item (running a program or script) on the other? Ah. Rather, there is only one (boolean) option, which is `close_on_execute`?

**Comment by DoTheEvo** [comment]
yeap, only one option, close_on_open acted exactly the same but I changed it cuz close_on_open sounded strange and stupid if you stopped and think about it - close on open
