### ISSUE TITLE
Restrict query to subtree

### ISSUE THREAD

**Issue by Jazoray** [DoTheEvo/ANGRYsearch#5]
I would like to search just a subtree of all my files, because i know that the file i'm looking for is somewhere "over there"

**Comment by DoTheEvo** [comment]
So write "over there"  in the search as well? A directory name, or a mount point name.. something that is present in the files full path...

The gif on the main page shows it in action.

**Comment by Jazoray** [comment]
oh durr. i should disable my unanimateGIF extension every now and then.
