### ISSUE TITLE
No config file?

### ISSUE THREAD

**Issue by bennypr0fane** [DoTheEvo/ANGRYsearch#54]
I can't find the config file in the location specified in docs ~/.config/angrysearch/angrysearch.conf under Manjaro/Arch Linux. In fact, there is no file containing the string "angry" at all in my  ~/ directory.

Here are the files created at installation (from /var/lib/pacman/local/angrysearch-1.0.1-1/files):
```
%FILES%
usr/
usr/bin/
usr/bin/angrysearch
usr/share/
usr/share/angrysearch/
usr/share/angrysearch/angrysearch.desktop
usr/share/angrysearch/angrysearch.py
usr/share/angrysearch/angrysearch.svg
usr/share/angrysearch/angrysearch_update_database.py
usr/share/angrysearch/qdarkstylesheet.qss
usr/share/angrysearch/resource_file.py
usr/share/angrysearch/scandir.py
usr/share/applications/
usr/share/applications/angrysearch.desktop
usr/share/pixmaps/
usr/share/pixmaps/angrysearch.svg
```

**Comment by DoTheEvo** [comment]
Config file is created on the first run / close, if deleted its recreated with defaults.
Also if you installed latest from github it would be named `angry_database.conf` but still in ~/.config/angrysearch
