### ISSUE TITLE
'Open path' does not work on files when using pcmanfm-qt filemanager

### ISSUE THREAD

**Issue by CottonEaster** [DoTheEvo/ANGRYsearch#55]
Hello!

I don't know whether this is an AngrySearch problem or a pcmanfm-qt problem but, when using AngrySearch's 'open path' function on a file, and when the file manager is set (globally and within AngrySearch) to pcmanfm-qt, then nothing happens. When the item in question is a _folder_, though, then 'open path' works. When I used nemo or indeed pcmanfm (the non 'qt' version), 'open with' worked for both folders and files.

AngrySearch version: unknown, but fairly recent, and from github.

**Comment by CottonEaster** [comment]
When I run angrySearch in the terminal, in says the following, even when angrySearch.conf specifies nemo as the filemanager

autodetected file manager: pcmanfm

I think this is the problem. I do not have pcmanfm installed anymore - but I _do_ have pcmanfm-qt.

**Comment by CottonEaster** [comment]
I know how to fix this. I do not know how to file pull requests, so I'll specify the code change here.

One needs to insert, in `/usr/share/angrysearch/angrysearch.py`, and between line 792 and line 793 - yielding a new line 793 - this:

      'pcmanfm-qt',

**Comment by DoTheEvo** [comment]
will check out

**Comment by DoTheEvo** [comment]
>when using AngrySearch's 'open path' function on a file, and when the file manager is set (globally and within AngrySearch) to pcmanfm-qt, then nothing happens. When the item in question is a folder, though, then 'open path' works. 

had a look, the issue was that in the end the program detected pcmanfm-qt but called pcmanfm to open the file

should be fixed now

>When I run angrySearch in the terminal, in says the following, even when angrySearch.conf specifies nemo as the filemanager

>autodetected file manager: pcmanfm

that is strange and should not happen, there was some issue with config file being named differently(angry_database.conf), so if you just tried not the release but recent commit using "clone or download" green button you might get that build and it might kinda ignore your config if you just kept writing in to the old one.

Otherwise it should never talk about autodetecting when you have something written in the config file `file_manager=blabla`

**Comment by CottonEaster** [comment]
_No dice._

More specifically: I just tried the git version, with an angrysearch.conf specifying no file manager, and I had the original problem, viz., angrySearch would not open the file manager. Moreover, angrySearch autodetected the file manager as 'pcmanfm', not 'pcmanfm-qt'. I discover though that I have an `angry_database.conf` on my system, too (though it does not specify a file manager either); which of the two config file should I keep and use?

_Solution_ - well, it worked for me: ensure that `pcmanfm-qt` precedes `pcmanfm` in the 'known_fm' list.

**Comment by DoTheEvo** [comment]
Alright, made that change and tested it, seems to be working.
Delete the `angry_database.conf`

**Comment by CottonEaster** [comment]
Thanks. It must be to do with how your search algorithm works - but I don't know Python (or your code, really).
