### ISSUE TITLE
how to exclude multiple directories from search

### ISSUE THREAD

**Issue by tigerider** [DoTheEvo/ANGRYsearch#56]
Hi, from explanation of the parameters in the config file:
"directories_excluded By default empty. Which directories to be ignored. ..."

How to exclude multiple directories from search?
I tried to add other directories in the config file by separating the additional paths by space, semicolon, comma, newline (with directories excluded copied to the next line). None seems to be working. 

Could you write a short explanation to clarify please. Thanks and keep up the great work.!

**Comment by DoTheEvo** [comment]
its space separated, test with `home mnt share usr` and you should see how very few results you get

are you editing in the file or through the update interface?
if through the file, you are likely not closing and relaunching the application to load the newly set settings

**Comment by tigerider** [comment]
Yes, that works exactly as described in the update interface. Thank you for immediately responding and clarifying.
Example of text to be entered into "ignored directories" box in update interface:
All of this in one single line:
/home/my-user-name/.kingsoft/office6/data/backup/ /media/my-user-name/MANJARO/ /usr/share/help/ /share /usr /home/my-user-name/.local
