### ISSUE TITLE
Typing " causes crash

### ISSUE THREAD

**Issue by g4jc** [DoTheEvo/ANGRYsearch#7]
Hello,
I just tried your program and I must say congrats and thanks for your work! It's the closest thing I've ever seen to a fast and decent windows-style search GUI in GNU/Linux. 

That said, I thought it might be possible to search for an explicit filename via "myfilename", but realized a bug when trying it.

To reproduce:
1) Make sure checkbox is checked
2) Type "
3) Get this in terminal:
----------------
autodetected file manager: thunar
Traceback (most recent call last):
  File "/usr/bin/angrysearch", line 57, in run
    (self.sql_query, self.number_of_results))
sqlite3.OperationalError: malformed MATCH expression: [*"*]
[1]    26812 abort (core dumped)  angrysearch
--------------

Presumably, the program should silently ignore the quotation mark without crashing.

**Comment by DoTheEvo** [comment]
Thanks for reporting this. Latest commit makes both single and double quotation marks do explicit word-bound searching, while bold text in search result should also account for this.

If you want to get it right away, just overwrite the content of angrysearch.py in your system, with the one from the [latest commit](https://raw.githubusercontent.com/DoTheEvo/ANGRYsearch/b7c6d53b013bd717766a603ab877a47760575151/angrysearch.py)

Thanks to tinkering with this, I also found out that theres a newer version of [sqlite FTS extension](https://www.sqlite.org/fts5.html), so there will probably be switch for that once its more wide spread...   it might bring more control over the search queries... but will see...

**Comment by g4jc** [comment]
Works great in latest versions, thanks for the fix! :+1:
