### ISSUE TITLE
Support keyboard navigation

### ISSUE THREAD

**Issue by cronaldo9999** [DoTheEvo/ANGRYsearch#8]
Hi,
Can you add some keyboard shortcut to focus the search input, please? Since I can use Tab to select search results, I think having a shortcut to focus back to the search input is a nice little feature.

**Comment by DoTheEvo** [comment]
Will do, browsers use `F6` `alt+D` `ctrl+L` for getting in to address bar
Those could be set here as well I believe

other alternative as I am think about it, is that tab key would only change active elements, pressing tab would cicle through `search-input -> results -> update button -> again search-inpput -> ...`
not through actual results, there would be expectation to use arrows up and down I guess

Another interesting idea I had some time ago and forgot about it was that just starting to type would automatically type in the search input, no matter where you are at that moment..  but not sure how viable that is

**Comment by Zzooouhh** [comment]
Could you also include a hotkey for Esc to close the whole application? Something like
`if event.key() == 16777216:
sys.exit(app.exec_())`
on line 515 of angrysearch.py, don't feel like making a pull request for such a minor (but practical!) change.

**Comment by DoTheEvo** [comment]
Will add, along with ctrl+Q
