### ISSUE TITLE
Feature request: add a way to show the program's version

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [DoTheEvo/ANGRYsearch#86]
First: thank you for the new release (version 1.0.3).

Next, and somewhat relatedly: unless I make a mistake, AngrySearch seems to lack the ability to tell the user which version of the program is running. It would be good were the program able to do this. (Then, for one thing, one would be able to check whether one had upgraded successfully.)

**Comment by DoTheEvo** [comment]
tray icon
right click...
should have put it to be visible in update menu or somewhere, but this is really just a project coasting on maintaining

**Comment by LinuxOnTheDesktop** [comment]
Ah. I have long disabled the program's tray icon. For, on my Linux Mint computers, it never worked properly - see #42.
