### ISSUE TITLE
Add new icons

### ISSUE THREAD

**Issue by Flajr** [DoTheEvo/ANGRYsearch#9]
Hello,
I was experimenting with icons. I tried to add new, (put instead of bundled ones, or in code add entry), but didn't figure it out. Is there a easy way to do this? I use to Lubuntu icons style. It's all what I miss in this outstanding software. Many thanks for reply.
[lubuntu_mimeicons.tar.gz](https://github.com/DoTheEvo/ANGRYsearch/files/238907/lubuntu_mimeicons.tar.gz)

**Comment by DoTheEvo** [comment]
there used to be an easy way, there was just folder with icon files which you could replace and it would work...
but then I found out I could bundle them all in to a single file, so for some foolish reason I did that, felt cleaner, now its bit more difficult to do...

* download and extract the latest release
* go in to ../resources/mimeicons/numix or whichever...
* replace icons there with your own
* go in to ../resources where you see the file `build_resource_file.qrc`
* get pyqt5 dev tools `sudo apt-get install pyqt5-dev-tools` assuming you are on lubuntu
* run this command to create the new resource file `pyrcc5 -no-compress build_resource_file.qrc -o resource_file.py`
* replace the resource file in /usr/share/angrysearch/resource_file.py with the newly created one

run angrysearch, switch to numix theme, or whichever one you replaced with your own icons

**Comment by Flajr** [comment]
Thank you working like a charm, now it's completely awesome!
