### ISSUE TITLE
ANGRYsearch didn't survive update to Ubuntu 24.4

### ISSUE THREAD

**Issue by githupjack** [DoTheEvo/ANGRYsearch#92]
What could I do, the output after starting it is as follows (... and it did work previously ... ): 
$ angrysearch
/usr/bin/angrysearch:1036: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  if column_to_sort_by is 0:
/usr/bin/angrysearch:1038: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  if revert_sort_order is 1:
/usr/bin/angrysearch:1043: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  if column_to_sort_by is 3:
/usr/bin/angrysearch:1045: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  if revert_sort_order is 1:
/usr/bin/angrysearch:1051: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  if column_to_sort_by is 2:
/usr/bin/angrysearch:1052: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  if revert_sort_order is 0:
QSocketNotifier: Can only be used with threads started with QThread
autodetected file manager: nautilus
Traceback (most recent call last):
  File "/usr/bin/angrysearch", line 1742, in <module>
    main()
  File "/usr/bin/angrysearch", line 1737, in main
    ui = AngryMainWindow()
         ^^^^^^^^^^^^^^^^^
  File "/usr/bin/angrysearch", line 661, in __init__
    self.init_gui()
  File "/usr/bin/angrysearch", line 911, in init_gui
    self.show_first_500()
  File "/usr/bin/angrysearch", line 1237, in show_first_500
    self.process_q_resuls('', tuppled_500)
  File "/usr/bin/angrysearch", line 1152, in process_q_resuls
    total = locale.format('%d', len(db_query_result), grouping=True)
            ^^^^^^^^^^^^^
AttributeError: module 'locale' has no attribute 'format'. Did you mean: '_format'?

**Comment by tw9mini** [comment]
Same.
The fix, however, could be quite easy:

> The locale.format() function is deprecated since Python 3.7: see issue https://github.com/python/cpython/issues/54588 for the rationale. IMO it's now time to remove this deprecated function: locale.format_string() can be used since Python 3.7.

**Comment by githupjack** [comment]
great. thanks!  (For all newbies like me:  rightclick open 'angrysearch' in /usr/bin with editor, go to search and replace and do it.  Save it, start ANGRYsearch).
